spring.application.name=booking-services
# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuración de Hibernate 
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

# Estrategia de nombres
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.port=8082

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui

server.url=http://localhost:8082
#server.url=http://host.docker.internal:8082

# Ejecuta siempre los scripts de inicialización al arrancar
spring.sql.init.mode=always

# Configuración del cliente HTTP para hotels-service
hotels-service.base-url=http://localhost:8081
