spring.application.name=reviews

#Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/reviews_db?useSSL=false&serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/db_hotelsbook
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuración de Hibernate 
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# Inyectar datos SQL al iniciar
spring.sql.init.data-locations=classpath:import-reviews.sql
spring.sql.init.mode=always

server.port=8081
# Configuración OpenAPI/Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.groups.enabled=true
springdoc.swagger-ui.url=/api/openapi.yaml
spring.web.resources.static-locations=classpath:/,classpath:/static/