spring.application.name=hotels-services

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/hotels_db?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuración de Hibernate 
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

# Estrategia de nombres
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.sql.init.data-locations=classpath:import-hotels.sql
spring.sql.init.mode=always

# Configuración OpenAPI/Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.groups.enabled=true
springdoc.openapi.file-path=api/openapi.yaml