-- Script de inicialización de datos para la tabla cities
INSERT INTO cities (name, country) VALUES
    ('Madrid', 'España'),
    ('Barcelona', 'España'),
    ('Sevilla', 'España'),
    ('Valencia', 'España'),
    ('Málaga', 'España'),
    ('París', 'Francia'),
    ('Lyon', 'Francia'),
    ('Marsella', 'Francia'),
    ('Niza', 'Francia'),
    ('Roma', 'Italia'),
    ('Milán', 'Italia'),
    ('Florencia', 'Italia'),
    ('Venecia', 'Italia'),
    ('Nápoles', 'Italia'),
    ('Lisboa', 'Portugal'),
    ('Oporto', 'Portugal'),
    ('Londres', 'Reino Unido'),
    ('Mánchester', 'Reino Unido'),
    ('Edimburgo', 'Reino Unido'),
    ('Berlín', 'Alemania'),
    ('Múnich', 'Alemania'),
    ('Fráncfort', 'Alemania'),
    ('Hamburgo', 'Alemania'),
    ('Ámsterdam', 'Países Bajos'),
    ('Róterdam', 'Países Bajos'),
    ('Bruselas', 'Bélgica'),
    ('Gante', 'Bélgica'),
    ('Viena', 'Austria'),
    ('Zúrich', 'Suiza'),
    ('Ginebra', 'Suiza'),
    ('Praga', 'República Checa'),
    ('Budapest', 'Hungría'),
    ('Varsovia', 'Polonia'),
    ('Cracovia', 'Polonia'),
    ('Atenas', 'Grecia'),
    ('Dublín', 'Irlanda'),
    ('Copenhague', 'Dinamarca'),
    ('Estocolmo', 'Suecia'),
    ('Oslo', 'Noruega'),
    ('Helsinki', 'Finlandia'),
    ('Nueva York', 'Estados Unidos'),
    ('Los Ángeles', 'Estados Unidos'),
    ('Chicago', 'Estados Unidos'),
    ('Miami', 'Estados Unidos'),
    ('Toronto', 'Canadá'),
    ('Vancouver', 'Canadá'),
    ('Tokio', 'Japón'),
    ('Kioto', 'Japón'),
    ('Sídney', 'Australia'),
    ('Buenos Aires', 'Argentina');