openapi: 3.0.0
info:
  title: Hotels Service API
  version: 1.0.0
  description: API para la gestión de ciudades y hoteles en el catálogo

servers:
  - url: http://localhost:8080
    description: Servidor local

tags:
  - name: Ciudades
    description: Endpoints para la gestión del catálogo de ciudades
  - name: Hoteles
    description: Endpoints para la gestión del catálogo de hoteles
  - name: Amenities
    description: Endpoints para la gestión de los servicios de los hoteles

paths:
  /api/cities:
    $ref: './paths/city-controller.yaml#/cities'
  /api/cities/{id}:
    $ref: './paths/city-controller.yaml#/cityById'
  /api/hotels:
    $ref: './paths/hotel-controller.yaml#/hotels'
  /api/hotels/{id}:
    $ref: './paths/hotel-controller.yaml#/hotelById'
  /api/amenities:
    $ref: './paths/amenity-controller.yaml#/amenities'
  /api/amenities/{id}:
    $ref: './paths/amenity-controller.yaml#/amenityById'